apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    {{- if .Values.ingress.gce.enabled }}
    cloud.google.com/backend-config: '{"default": "{{ include "budibase.fullname" . }}"}'
    {{- end }}
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: budibase-proxy
  name: proxy-service
spec:
  ports:
  - name: {{ .Values.services.proxy.port | quote }}
    port: {{ .Values.services.proxy.port }}
    targetPort: {{ .Values.services.proxy.port }}
  selector:
    app.kubernetes.io/name: budibase-proxy
{{- if .Values.ingress.gce }}
  type: NodePort
{{- end }}
status:
  loadBalancer: {}